# Generated by Django 6.0.3 on 2026-03-11 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('google_count', models.IntegerField(default=0)),
                ('brave_count', models.IntegerField(default=0)),
                ('tavily_count', models.IntegerField(default=0)),
            ],
        ),
    ]
